[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ai_agent = "8sZuVSqHEvhRTn1syQwgbwfwqr8PNjdty4a6o2BzL1ox"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
